import type { BusinessCategorySeed } from "./business-type-matcher";

// User-facing business categories for onboarding autocomplete.
// Primary labels follow common local-business language from Google Business
// Profile, Schema.org LocalBusiness, OpenStreetMap shop/amenity conventions,
// with NAICS codes attached only as secondary metadata.
export const businessCategorySeeds = [
  { id: "software-company", label: "Software company", playbookId: "saas", aliases: ["saas", "software as a service", "software platform", "software product", "app company", "app", "mobile app", "subscription app", "web app", "subscription software", "b2b software", "cloud software", "cloud platform", "developer tools", "digital product", "product business", "marketplace platform", "online marketplace"], naicsCodes: ["513210", "541511"] },
  { id: "ai-company", label: "AI company", playbookId: "saas", aliases: ["ai", "artificial intelligence company", "ai company", "ai platform", "machine learning company", "ml platform", "automation platform", "ai startup"], naicsCodes: ["541511", "541715"] },
  { id: "it-support", label: "IT support company", playbookId: "saas", aliases: ["it", "it support", "it services", "managed it services", "managed service provider", "msp", "it help desk", "technical support", "computer support", "technology consultancy"], naicsCodes: ["541513", "541519"] },
  { id: "cybersecurity", label: "Cybersecurity company", playbookId: "saas", aliases: ["cyber security", "security platform", "managed security", "security consultancy", "identity platform"], naicsCodes: ["541519", "518210"] },
  { id: "digital-agency", label: "Digital agency", playbookId: "general", aliases: ["web design agency", "web agency", "marketing agency", "seo agency", "seo", "creative agency", "advertising agency", "digital marketing"], naicsCodes: ["541810", "541613", "541430"] },
  { id: "data-analytics", label: "Data analytics company", playbookId: "saas", aliases: ["analytics platform", "data platform", "business intelligence", "bi platform", "reporting platform"], naicsCodes: ["518210", "541511"] },
  { id: "telecom-company", label: "Telecommunications company", playbookId: "saas", aliases: ["telecom", "telecommunications", "phone provider", "broadband provider", "internet service provider", "isp", "communications provider"], naicsCodes: ["517111", "517112", "517810"] },
  { id: "media-company", label: "Media company", playbookId: "general", aliases: ["media", "media company", "publisher", "publishing company", "publishing", "podcast network", "podcast", "podcasting", "content studio", "content creator", "creator business", "creator", "production studio"], naicsCodes: ["512110", "513110", "516210"] },
  { id: "gaming-company", label: "Gaming company", playbookId: "saas", aliases: ["game studio", "games studio", "video game company", "gaming", "game developer"], naicsCodes: ["513210"] },

  { id: "dental-clinic", label: "Dental clinic", playbookId: "healthcare", aliases: ["dentist", "dental practice", "orthodontist", "cosmetic dentistry", "hygienist", "emergency dentist"], naicsCodes: ["621210"] },
  { id: "medical-practice", label: "Medical practice", playbookId: "healthcare", aliases: ["gp", "gp practice", "doctor office", "doctors office", "doctor surgery", "urgent care", "primary care", "family doctor", "private clinic", "medical clinic", "health clinic", "walk in clinic"], naicsCodes: ["621111", "621493"] },
  { id: "physiotherapy-clinic", label: "Physiotherapy clinic", playbookId: "healthcare", aliases: ["physio", "physical therapy", "physical therapist", "occupational therapy", "rehab clinic", "sports therapy"], naicsCodes: ["621340"] },
  { id: "mental-health-clinic", label: "Mental health clinic", playbookId: "healthcare", aliases: ["therapy clinic", "therapist", "counselling practice", "counseling practice", "psychologist", "psychotherapy", "outpatient mental health"], naicsCodes: ["621330", "621420"] },
  { id: "optician", label: "Optician", playbookId: "healthcare", aliases: ["optometrist", "eye clinic", "optical shop", "glasses shop", "vision care"], naicsCodes: ["456130", "621320"] },
  { id: "veterinary-clinic", label: "Veterinary clinic", playbookId: "healthcare", aliases: ["vet", "vet practice", "animal hospital", "pet clinic"], naicsCodes: ["541940"] },
  { id: "aesthetic-clinic", label: "Aesthetic clinic", playbookId: "healthcare", aliases: ["skin clinic", "med spa", "cosmetic clinic", "laser clinic", "injectables clinic"], naicsCodes: ["812113", "621399"] },
  { id: "home-care", label: "Home care agency", playbookId: "healthcare", aliases: ["home health care", "care agency", "domiciliary care", "senior care"], naicsCodes: ["621610", "624120"] },
  { id: "diagnostic-clinic", label: "Diagnostic clinic", playbookId: "healthcare", aliases: ["medical laboratory", "blood test clinic", "imaging centre", "imaging center", "mri clinic", "xray clinic"], naicsCodes: ["621511", "621512"] },

  { id: "hospitality-business", label: "Hospitality business", playbookId: "hospitality", aliases: ["hospitality", "hospitality business", "leisure business", "local consumer business", "local business", "local consumer"], blockedTerms: ["hospital"], naicsCodes: ["72"] },
  { id: "food-service", label: "Food service business", playbookId: "hospitality", aliases: ["food", "food business", "food service", "food services"], naicsCodes: ["722"] },
  { id: "restaurant", label: "Restaurant", playbookId: "hospitality", aliases: ["restaurant group", "bistro", "fine dining", "casual dining", "family restaurant"], naicsCodes: ["722511"] },
  { id: "cafe", label: "Cafe", playbookId: "hospitality", aliases: ["coffee shop", "tea room", "snack bar", "bakery cafe"], naicsCodes: ["722515"] },
  { id: "takeaway", label: "Takeaway restaurant", playbookId: "hospitality", aliases: ["fast food", "food delivery", "pizzeria", "sandwich shop", "quick service restaurant"], naicsCodes: ["722513"] },
  { id: "bar-pub", label: "Bar or pub", playbookId: "hospitality", aliases: ["bar", "pub", "cocktail bar", "wine bar", "nightclub", "brewery taproom"], naicsCodes: ["722410"] },
  { id: "hotel", label: "Hotel", playbookId: "hospitality", aliases: ["hotel reservations", "front desk", "concierge", "room booking", "guest accommodation"], naicsCodes: ["721110"] },
  { id: "guest-house", label: "Guest house or B&B", playbookId: "hospitality", aliases: ["bed and breakfast", "b&b", "guest house", "inn", "hostel"], naicsCodes: ["721191", "721199"] },
  { id: "event-venue", label: "Event venue", playbookId: "hospitality", aliases: ["wedding venue", "conference venue", "events company", "event planner", "event planning", "private events", "banquet hall"], naicsCodes: ["711310", "531120"] },
  { id: "catering-company", label: "Catering company", playbookId: "hospitality", aliases: ["caterer", "contract catering", "event catering", "mobile food vendor", "food truck"], naicsCodes: ["722310", "722330"] },
  { id: "travel-agency", label: "Travel agency", playbookId: "hospitality", aliases: ["tour operator", "tourism", "tourism business", "tour guide", "tour company", "reservation desk", "travel agent", "holiday booking"], naicsCodes: ["561510"] },
  { id: "visitor-attraction", label: "Visitor attraction", playbookId: "hospitality", aliases: ["tourist attraction", "visitor attraction", "activities", "activity centre", "activity center", "leisure centre", "leisure center"], naicsCodes: ["713110", "713990"] },
  { id: "gym", label: "Gym or fitness centre", playbookId: "general", aliases: ["gym", "fitness center", "fitness centre", "fitness studio", "health club", "personal training studio", "personal trainer", "pilates", "yoga studio", "wellness center", "wellness centre"], naicsCodes: ["713940", "812191"] },

  { id: "estate-agency", label: "Estate agency", playbookId: "estate", aliases: ["estate agent", "real estate agency", "real estate agent", "realtor", "property sales", "home valuation", "valuation requests"], naicsCodes: ["531210"] },
  { id: "lettings-agency", label: "Lettings agency", playbookId: "estate", aliases: ["letting agent", "rental agency", "tenant enquiries", "landlord services"], naicsCodes: ["531210", "531311"] },
  { id: "property-management", label: "Property management company", playbookId: "estate", aliases: ["residential property manager", "commercial property management", "block management", "strata management", "facilities management"], naicsCodes: ["531311", "531312"] },
  { id: "serviced-accommodation", label: "Serviced accommodation", playbookId: "estate", aliases: ["short term rental", "holiday lets", "serviced apartments", "apartment rentals"], naicsCodes: ["531110", "721199"] },
  { id: "surveyors", label: "Surveyors", playbookId: "estate", aliases: ["chartered surveyor", "property surveyor", "real estate appraiser", "property valuer"], naicsCodes: ["531320", "541350"] },
  { id: "conveyancing", label: "Conveyancing firm", playbookId: "estate", aliases: ["conveyancer", "property solicitor", "title company", "settlement office"], naicsCodes: ["541191"] },

  { id: "financial-adviser", label: "Financial adviser", playbookId: "financial", aliases: ["financial advisor", "wealth manager", "investment adviser", "investment advisor", "ifa", "pension adviser", "retirement planning"], naicsCodes: ["523940"] },
  { id: "financial-services", label: "Financial services firm", playbookId: "financial", aliases: ["financial services", "finance", "finance company", "financial firm", "banking services", "banking"], naicsCodes: ["52"] },
  { id: "accountant", label: "Accountancy firm", playbookId: "financial", aliases: ["accountant", "accounting", "accounting firm", "accountancy", "cpa", "certified public accountant", "bookkeeper", "bookkeeping", "tax adviser", "tax advisor", "payroll bureau"], naicsCodes: ["541211", "541213", "541214", "541219"] },
  { id: "insurance-broker", label: "Insurance broker", playbookId: "financial", aliases: ["insurance agency", "claims broker", "commercial insurance", "life insurance", "home insurance", "motor insurance"], naicsCodes: ["524210"] },
  { id: "mortgage-broker", label: "Mortgage broker", playbookId: "financial", aliases: ["mortgage adviser", "mortgage advisor", "home loan broker", "loan broker"], naicsCodes: ["522310"] },
  { id: "bank", label: "Bank or credit union", playbookId: "financial", aliases: ["bank", "retail bank", "commercial bank", "credit union", "lender", "loan provider"], naicsCodes: ["522110", "522130", "522180"] },
  { id: "payments-company", label: "Payments company", playbookId: "financial", aliases: ["payment provider", "card provider", "card issuer", "fintech", "payment platform"], naicsCodes: ["522210", "522320"] },

  { id: "bookshop", label: "Bookshop", playbookId: "bookstore", aliases: ["bookstore", "book store", "independent bookshop", "bookseller", "book retailer", "comic book shop", "academic bookshop"], naicsCodes: ["459210"] },
  { id: "retail-business", label: "Retail business", playbookId: "retail", aliases: ["retail", "retailer", "retail shop", "retail store", "online retail", "high street shop", "consumer retail"], naicsCodes: ["44", "45"] },
  { id: "clothing-store", label: "Clothing store", playbookId: "retail", aliases: ["clothes shop", "apparel store", "fashion store", "boutique", "dress shop", "menswear", "womenswear", "bridal shop"], naicsCodes: ["458110"] },
  { id: "shoe-store", label: "Shoe store", playbookId: "retail", aliases: ["footwear shop", "shoe shop", "trainer shop", "sneaker store"], naicsCodes: ["458210"] },
  { id: "jewellery-store", label: "Jewellery store", playbookId: "retail", aliases: ["jewelry store", "jewellery shop", "watch shop", "jewellery repair", "jewelry repair"], naicsCodes: ["458310", "811430"] },
  { id: "online-store", label: "Online store", playbookId: "retail", aliases: ["ecommerce", "e-commerce", "shopify store", "web shop", "online shop", "marketplace seller", "d2c brand", "direct to consumer"], naicsCodes: ["455219"] },
  { id: "grocery-store", label: "Grocery store", playbookId: "retail", aliases: ["supermarket", "food shop", "convenience store", "corner shop", "greengrocer"], naicsCodes: ["445110", "445131", "445230"] },
  { id: "bakery", label: "Bakery", playbookId: "retail", aliases: ["bake shop", "cake shop", "pastry shop"], naicsCodes: ["445291"] },
  { id: "butcher", label: "Butcher", playbookId: "retail", aliases: ["meat shop", "butchers", "fishmonger", "seafood shop"], naicsCodes: ["445240", "445250"] },
  { id: "liquor-store", label: "Wine, beer or liquor store", playbookId: "retail", aliases: ["wine shop", "beer shop", "liquor store", "off licence"], naicsCodes: ["445320"] },
  { id: "pharmacy", label: "Pharmacy", playbookId: "healthcare", aliases: ["chemist", "drug store", "drugstore", "prescription pharmacy"], naicsCodes: ["456110"] },
  { id: "beauty-supply", label: "Beauty supply store", playbookId: "retail", aliases: ["cosmetics store", "perfume shop", "makeup store", "skincare shop", "beauty retailer"], naicsCodes: ["456120"] },
  { id: "electronics-store", label: "Electronics store", playbookId: "retail", aliases: ["appliance store", "phone shop", "mobile phone shop", "computer store", "camera shop"], naicsCodes: ["449210"] },
  { id: "furniture-store", label: "Furniture store", playbookId: "retail", aliases: ["home furniture shop", "homeware shop", "home furnishings", "flooring store", "carpet shop"], naicsCodes: ["449110", "449121", "449129"] },
  { id: "hardware-store", label: "Hardware store", playbookId: "retail", aliases: ["diy store", "building supplies", "paint shop", "tool shop"], naicsCodes: ["444110", "444120"] },
  { id: "garden-centre", label: "Garden centre", playbookId: "retail", aliases: ["garden center", "garden store", "plant nursery", "plant shop"], naicsCodes: ["444180"] },
  { id: "florist", label: "Florist", playbookId: "retail", aliases: ["flower shop", "floral shop", "flower delivery", "wedding florist"], naicsCodes: ["459310"] },
  { id: "pet-store", label: "Pet store", playbookId: "retail", aliases: ["pet shop", "pet supplies", "aquarium shop"], naicsCodes: ["459910"] },
  { id: "gift-shop", label: "Gift shop", playbookId: "retail", aliases: ["souvenir shop", "craft shop", "hobby shop", "toy shop", "game shop"], naicsCodes: ["459420", "459120"] },
  { id: "sports-store", label: "Sports shop", playbookId: "retail", aliases: ["sporting goods store", "outdoor shop", "bike shop", "bicycle shop"], naicsCodes: ["459110", "459991"] },
  { id: "car-dealer", label: "Car dealership", playbookId: "retail", aliases: ["car dealer", "auto dealer", "vehicle dealership", "used car dealer", "used auto dealer"], naicsCodes: ["441110", "441120"] },
  { id: "auto-parts", label: "Auto parts store", playbookId: "retail", aliases: ["car parts store", "tire shop", "tyre shop", "motor parts"], naicsCodes: ["441330"] },
  { id: "petrol-station", label: "Petrol station", playbookId: "retail", aliases: ["gas station", "fuel station", "service station", "ev charging station"], naicsCodes: ["457110", "457120"] },

  { id: "hair-salon", label: "Hair salon", playbookId: "general", aliases: ["hairdresser", "barber", "barbershop", "hair stylist"], naicsCodes: ["812111"] },
  { id: "beauty-salon", label: "Beauty salon", playbookId: "general", aliases: ["nail salon", "esthetician", "aesthetician", "lash studio", "brow studio"], naicsCodes: ["812112"] },
  { id: "spa", label: "Spa", playbookId: "general", aliases: ["day spa", "massage spa", "wellness spa"], naicsCodes: ["812113"] },
  { id: "funeral-home", label: "Funeral home", playbookId: "general", aliases: ["funeral director", "funeral services", "crematorium"], naicsCodes: ["812210"] },
  { id: "laundry", label: "Laundry or dry cleaner", playbookId: "general", aliases: ["laundrette", "laundromat", "laundry service", "dry cleaner", "dry cleaning"], naicsCodes: ["812310", "812320"] },
  { id: "cleaning-company", label: "Cleaning company", playbookId: "general", aliases: ["cleaner", "janitorial service", "commercial cleaning", "house cleaning", "carpet cleaner"], naicsCodes: ["561720", "561740"] },
  { id: "landscaping", label: "Landscaping company", playbookId: "general", aliases: ["landscaper", "gardener", "lawn care", "grounds maintenance"], naicsCodes: ["561730"] },
  { id: "pest-control", label: "Pest control company", playbookId: "general", aliases: ["pest control", "exterminator", "vermin control"], naicsCodes: ["561710"] },
  { id: "security-company", label: "Security company", playbookId: "general", aliases: ["security", "security guard", "alarm company", "locksmith", "private security"], naicsCodes: ["561612", "561621", "561622"] },

  { id: "plumber", label: "Plumbing company", playbookId: "general", aliases: ["plumber", "plumbing contractor", "heating engineer", "hvac contractor", "air conditioning contractor"], naicsCodes: ["238220"] },
  { id: "electrician", label: "Electrical contractor", playbookId: "general", aliases: ["electrician", "electrical contractor", "electrical services"], naicsCodes: ["238210"] },
  { id: "builder", label: "Building contractor", playbookId: "general", aliases: ["builder", "general contractor", "construction company", "construction contractor", "civil construction", "commercial construction", "home builder", "commercial builder"], naicsCodes: ["236115", "236118", "236220"] },
  { id: "painter-decorator", label: "Painter and decorator", playbookId: "general", aliases: ["painter", "decorator", "painting contractor"], naicsCodes: ["238320"] },
  { id: "roofer", label: "Roofing contractor", playbookId: "general", aliases: ["roofer", "roof repairs", "roofing company"], naicsCodes: ["238160"] },
  { id: "carpenter", label: "Carpenter", playbookId: "general", aliases: ["joiner", "carpentry", "joinery", "cabinet maker"], naicsCodes: ["238350", "337110"] },
  { id: "repair-service", label: "Repair service", playbookId: "general", aliases: ["repair", "repairs", "repair company", "repair service", "maintenance service", "watch repair"], naicsCodes: ["811"] },
  { id: "mechanic", label: "Auto repair shop", playbookId: "general", aliases: ["mechanic", "garage", "car repair", "body shop", "collision repair", "mot centre", "automotive repair", "vehicle repair"], naicsCodes: ["811111", "811121"] },
  { id: "appliance-repair", label: "Appliance repair company", playbookId: "general", aliases: ["home appliance repair", "electronics repair", "phone repair", "computer repair"], naicsCodes: ["811411", "811210"] },

  { id: "school", label: "School", playbookId: "general", aliases: ["primary school", "elementary school", "secondary school", "private school"], naicsCodes: ["611110"] },
  { id: "college-university", label: "College or university", playbookId: "general", aliases: ["college", "university", "higher education"], naicsCodes: ["611310"] },
  { id: "training-provider", label: "Training provider", playbookId: "general", aliases: ["training company", "tutoring business", "driving school", "language school", "music school"], naicsCodes: ["611430", "611691", "611699"] },
  { id: "nursery-childcare", label: "Nursery or childcare centre", playbookId: "general", aliases: ["nursery", "daycare", "child care centre", "child care center", "childcare center", "preschool"], naicsCodes: ["624410"] },
  { id: "recruitment-agency", label: "Recruitment agency", playbookId: "general", aliases: ["staffing agency", "employment agency", "temp agency", "headhunter", "recruiter", "recruiting agency"], naicsCodes: ["561311", "561312"] },
  { id: "law-firm", label: "Law firm", playbookId: "general", aliases: ["law", "lawyer", "solicitor", "attorney", "legal practice", "legal services"], naicsCodes: ["541110"] },
  { id: "consulting-firm", label: "Consulting firm", playbookId: "general", aliases: ["consulting", "consultant", "consultancy", "consulting firm", "business consulting", "management consulting", "operations consulting", "professional services", "professional services firm"], naicsCodes: ["541611", "541618"] },
  { id: "architect", label: "Architecture firm", playbookId: "general", aliases: ["architect", "architectural practice", "interior designer"], naicsCodes: ["541310", "541410"] },
  { id: "engineering-firm", label: "Engineering firm", playbookId: "general", aliases: ["engineer", "civil engineer", "structural engineer", "mechanical engineering", "engineering consultancy"], naicsCodes: ["541330"] },
  { id: "photography-studio", label: "Photography studio", playbookId: "general", aliases: ["photographer", "portrait studio", "commercial photographer"], naicsCodes: ["541921", "541922"] },

  { id: "manufacturer", label: "Manufacturer", playbookId: "general", aliases: ["manufacturing", "manufacturing company", "factory", "production company", "industrial manufacturer", "auto manufacturer", "automotive manufacturer", "automotive supplier", "aerospace", "aerospace manufacturer", "defense contractor", "defence contractor", "machine shop", "metal fabrication", "plastic injection molding"], naicsCodes: ["31", "32", "33"] },
  { id: "chemical-manufacturer", label: "Chemical manufacturer", playbookId: "general", aliases: ["chemicals", "chemical manufacturer", "chemical distributor", "industrial chemicals"], naicsCodes: ["325"] },
  { id: "packaging-manufacturer", label: "Packaging manufacturer", playbookId: "general", aliases: ["packaging", "packaging manufacturer", "packaging supplier", "corrugated packaging"], naicsCodes: ["322211", "326112"] },
  { id: "food-manufacturer", label: "Food manufacturer", playbookId: "general", aliases: ["food producer", "food factory", "food processing"], naicsCodes: ["311"] },
  { id: "soft-drink-manufacturer", label: "Soft drink manufacturer", playbookId: "general", aliases: ["soft drink manufacturing", "soft drink producer", "beverage manufacturer", "soda manufacturer"], naicsCodes: ["312111"], blockedTerms: ["software", "software as a service", "saas"] },
  { id: "wholesaler", label: "Wholesaler", playbookId: "general", aliases: ["wholesale distributor", "distribution company", "trade supplier", "industrial distributor", "building materials supplier", "plumbing supplies wholesale"], naicsCodes: ["42"] },
  { id: "logistics-company", label: "Logistics company", playbookId: "general", aliases: ["3pl", "third party logistics", "courier", "delivery company", "freight company", "freight forwarding", "freight forwarder", "shipping company", "transport company", "trucking company", "haulage company", "warehouse", "warehousing", "fulfilment company", "fulfillment company", "fulfillment center", "supply chain", "cold chain logistics", "last mile delivery"], naicsCodes: ["492110", "493110", "484"] },
  { id: "healthcare-provider", label: "Healthcare provider", playbookId: "healthcare", aliases: ["healthcare", "health care", "healthcare provider", "hospital", "clinic", "medical centre", "medical center"], naicsCodes: ["62"] },
  { id: "nonprofit", label: "Nonprofit organisation", playbookId: "general", aliases: ["nonprofit", "non profit", "non-profit", "not for profit", "ngo", "charity", "charitable organisation", "charitable organization", "community organization", "foundation"], naicsCodes: ["813"] },
  { id: "government-agency", label: "Government agency", playbookId: "general", aliases: ["government", "government agency", "government office", "public agency", "public sector", "public-sector", "local authority", "city council", "local council", "council", "municipality", "civic services"], naicsCodes: ["92"] },
  { id: "energy-company", label: "Energy company", playbookId: "general", aliases: ["energy", "renewable energy", "solar energy company", "wind energy", "oil and gas", "utility", "utilities", "utility company", "water utility", "power company", "electric utility", "gas utility", "solar company", "solar"], naicsCodes: ["221", "237130"] }
] as const satisfies readonly BusinessCategorySeed[];
